name: Update Base Image for AWS Lambda and push to DockerHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Build and Push to DockerHub Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Base Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/python-base-eval-layer
          build-args: |
            INVOKER_ID=${{ secrets.INVOKER_ID }}
            INVOKER_KEY=${{ secrets.INVOKER_KEY }}
            INVOKER_REGION=${{ secrets.INVOKER_REGION }}
